language: node_js
node_js:
  - "10"
branches:
  only:
    - master
install:
  - yarn install
script:
  - yarn build
deploy:
  provider: pages:git
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  on:
    branch: master
